#!/bin/bash
set -e

DEBUG=${DEBUG:-false}
$DEBUG && set -x || set +x

BASE_DIR=`cd "$(dirname "$0")"; pwd`

_publish() {
  local published_dir=`mktemp -d`
  local remote_repo=`git config --get remote.origin.url`

  if [ ".$remote_repo" = "." ]
  then
    echo 'The remote repository is not configured!'
    return 1
  fi

  mkdir -p "$published_dir"

  cd build/asciidoc/html5
  rsync -am \
    --include='**/' \
    --include='/index.html' \
    --include='/images/**' \
    --exclude='*' \
    . "$published_dir"/
  cd - &> /dev/null

  cd build/asciidoc/pdf
  cp index.pdf "$published_dir"/spring-cloud-dataflow-tutorial.pdf
  cd - &> /dev/null

  tree -a "$published_dir"

  local msg="Published at `date`"
  cd "$published_dir"
  git init
  git add -A
  git commit -m "$msg"
  git push --force $remote_repo master:gh-pages
  cd - &> /dev/null
}

cd "$BASE_DIR"
_publish
